-- MySQL Script generated by MySQL Workbench
-- Tue Jun 13 18:56:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookdb` DEFAULT CHARACTER SET utf8 ;
USE `bookdb` ;

-- -----------------------------------------------------
-- Table `bookdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookdb`.`user` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `fname` VARCHAR(12) NOT NULL,
  `lname` VARCHAR(12) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookdb`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookdb`.`book` (
  `idbook` INT(10) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) NOT NULL,
  `img` VARCHAR(100) NOT NULL,
  `author` VARCHAR(20) NOT NULL,
  `price` DOUBLE NOT NULL,
  `descri` VARCHAR(500) NOT NULL,
  `ISBN` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`idbook`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookdb`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookdb`.`cart` (
  `idcart` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) NOT NULL,
  `book_idbook` INT(10) NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`idcart`),
  INDEX `fk_cart_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_cart_book1_idx` (`book_idbook` ASC) VISIBLE,
  CONSTRAINT `fk_cart_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `bookdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_book1`
    FOREIGN KEY (`book_idbook`)
    REFERENCES `bookdb`.`book` (`idbook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
